[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y cmake clang perl libssl-dev"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y cmake clang perl libssl-dev"
]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "apt-get update && apt-get install -y cmake clang perl"
]

[target.x86_64-apple-darwin]
pre-build = [
    "apt-get update && apt-get install -y cmake clang perl"
]

[target.aarch64-apple-darwin]
pre-build = [
    "apt-get update && apt-get install -y cmake clang perl"
]
